# Generated by Django 5.0 on 2024-02-29 11:28

import base.models.MenuItem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='weight_in_grams',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='cooking_time',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Время готовки'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='stop_list',
            field=models.BooleanField(default=False, verbose_name='Стоп лист'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default=base.models.MenuItem.get_default_image, null=True, upload_to='menu_item/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='menuitemprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='menuitemprice',
            name='size_description',
            field=models.CharField(max_length=255, verbose_name='Описание'),
        ),
    ]
