# Generated by Django 5.0 on 2024-03-10 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_menuitem_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurateurFormInLendingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phoneOrMessenger', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.RemoveField(
            model_name='restaurateur',
            name='image',
        ),
        migrations.AddField(
            model_name='restaurateur',
            name='phoneOrMessenger',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
