# Generated by Django 5.0 on 2024-02-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_base_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default='/noimage4.png', null=True, upload_to='menu_item/', verbose_name='Картика'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='weight_in_grams',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
