# Generated by Django 5.0 on 2024-02-14 22:57

import base.models.MenuItem
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_menuitem_image_alter_menuitem_weight_in_grams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, default=base.models.MenuItem.get_default_image, null=True, upload_to='menu_item/', verbose_name='Картика'),
        ),
    ]
