# Generated by Django 5.0 on 2024-02-17 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_menuitemprice_menu_item_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemprice',
            name='menu_item_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='base.menuitem'),
        ),
        migrations.AlterField(
            model_name='menuitemprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='menuitemprice',
            name='size_description',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
